#!/usr/bin/env python3
"""Regenerate assets/propose.css from the mockup stylesheet (propose-lp/src/styles.css).

    python3 shopify-theme/tools/sync_css.py

The mockup is the source of truth for the design. The Shopify build differs only in:
  - reveal animations hide content only when JS is running (.js class set by the layout)
  - no hash-router views
  - a few rules for Shopify-only markup (appended below)
"""
import os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
SRC = os.path.join(ROOT, "propose-lp/src/styles.css")
OUT = os.path.join(ROOT, "shopify-theme/assets/propose.css")

REPLACE = [
    ("/* =====================================================================\n   世界のプロポーズプラン — styles",
     "/* =====================================================================\n   世界のプロポーズプラン — styles (Shopify build, generated by shopify-theme/tools/sync_css.py\n   from propose-lp/src/styles.css — edit the mockup stylesheet, then re-run the script)\n   Loaded only by layout/propose.liquid, so it never touches the main theme."),
    (".view { display: none; }\n.view.is-active { display: block; }\n.reveal { opacity: 0;", ".js .reveal { opacity: 0;"),
    (".reveal.is-in { opacity: 1; transform: none; }", ".js .reveal.is-in { opacity: 1; transform: none; }"),
    ("@media (max-width: 899px) { .reveal { transform: none; }", "@media (max-width: 899px) { .js .reveal { transform: none; }"),
    ("  .reveal, .reveal-img img", "  .js .reveal, .reveal-img img"),
]

ADDITIONS = """
/* ---------- Shopify build additions ---------- */
section[id], #avail { scroll-margin-top: 72px; }
@media (min-width: 960px) { section[id] { scroll-margin-top: 84px; } }
.photo .pp-placeholder { position: absolute; inset: 0; width: 100%; height: 100%; fill: var(--off); background: var(--paper-deep); }
.bk-error { margin: 0 0 20px; padding: 14px 16px; border: 1px solid var(--few); color: var(--few); font-size: .86rem; line-height: 1.8; background: var(--white); }
.pp-booking .bk-main { min-height: 60vh; }
.theme-results:not(.is-open) { display: none; }
"""


def main():
    css = open(SRC, encoding="utf-8").read()
    for old, new in REPLACE:
        if css.count(old) != 1:
            raise SystemExit("expected exactly one occurrence of: %r" % old[:60])
        css = css.replace(old, new)
    open(OUT, "w", encoding="utf-8").write(css.rstrip() + "\n" + ADDITIONS)
    print("wrote", os.path.relpath(OUT, ROOT))


if __name__ == "__main__":
    main()
